-- Migration: Add comprehensive Hackathon configuration fields to public.hackathons table
ALTER TABLE public.hackathons
  ADD COLUMN IF NOT EXISTS theme TEXT,
  ADD COLUMN IF NOT EXISTS domain TEXT,
  ADD COLUMN IF NOT EXISTS organizing_department TEXT,
  ADD COLUMN IF NOT EXISTS mode VARCHAR(50) DEFAULT 'Offline',
  ADD COLUMN IF NOT EXISTS external_link TEXT,
  ADD COLUMN IF NOT EXISTS abstract_submission_deadline TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS project_submission_deadline TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS demo_pitch_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS maximum_participants INT,
  ADD COLUMN IF NOT EXISTS eligibility_type VARCHAR(100) DEFAULT 'College Students',
  ADD COLUMN IF NOT EXISTS allowed_departments TEXT,
  ADD COLUMN IF NOT EXISTS allowed_years TEXT,
  ADD COLUMN IF NOT EXISTS allowed_colleges TEXT,
  ADD COLUMN IF NOT EXISTS rules TEXT,
  ADD COLUMN IF NOT EXISTS participation_guidelines TEXT,
  ADD COLUMN IF NOT EXISTS submission_guidelines TEXT,
  ADD COLUMN IF NOT EXISTS judging_criteria TEXT,
  ADD COLUMN IF NOT EXISTS code_of_conduct TEXT,
  ADD COLUMN IF NOT EXISTS problem_statement_description TEXT,
  ADD COLUMN IF NOT EXISTS required_tech_stack TEXT,
  ADD COLUMN IF NOT EXISTS github_url_required BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS demo_video_required BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS ppt_required BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS report_required BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS live_demo_required BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS prize_1st TEXT,
  ADD COLUMN IF NOT EXISTS prize_2nd TEXT,
  ADD COLUMN IF NOT EXISTS prize_3rd TEXT,
  ADD COLUMN IF NOT EXISTS special_prizes TEXT;
